name: Build Push

on:
  push:
    branches-ignore:
      - master

jobs:
  check-build-type:

    runs-on: ubuntu-latest
    outputs:
      branch: ${{ steps.check_step.outputs.branch }}
      build-type: ${{ steps.check_step.outputs.build-type }}

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get current branch
        id: check_step
        run: |
          branch=$(git for-each-ref --count 1 --sort=committerdate refs/heads/ --format='%(refname:short)')
          echo "::set-output name=branch::$branch"
          echo "Branch is $branch."
          git clone https://github.com/Kas-tle/Geyser.git --branch $branch --single-branch
          if [[ -f "Geyser/pom.xml" ]]; then
            build_type="maven"
            echo "::set-output name=build-type::$build_type"
          elif [[ -f "Geyser/build.gradle.kts" ]]; then
            build_type="gradle"
            echo "::set-output name=build-type::$build_type"
          else
            build_type="none"
            echo "::set-output name=build-type::$build_type"
          fi


  maven-build:
    runs-on: ubuntu-latest
    needs: check-build-type
    if: ${{ needs.check-build-type.outputs.build-type == 'maven' }}
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Set up JDK 16
        uses: actions/setup-java@v1
        with:
          java-version: 16
      - name: Build with Maven
        env: 
          BRANCH: ${{ needs.check-build-type.outputs.branch }}
        run: |
          git clone https://github.com/Kas-tle/Geyser.git --branch $BRANCH --single-branch
          cd Geyser
          git submodule update --init --recursive
          mvn -B package -T 2C
      - name: Archive artifacts (Geyser Standalone)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Standalone
          path: Geyser/bootstrap/standalone/target/Geyser.jar
      - name: Archive artifacts (Geyser Spigot)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Spigot
          path: Geyser/bootstrap/spigot/target/Geyser-Spigot.jar
      - name: Archive artifacts (Geyser BungeeCord)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser BungeeCord
          path: Geyser/bootstrap/bungeecord/target/Geyser-BungeeCord.jar
      - name: Archive artifacts (Geyser Sponge)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Sponge
          path: Geyser/bootstrap/sponge/target/Geyser-Sponge.jar
      - name: Archive artifacts (Geyser Velocity)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Velocity
          path: Geyser/bootstrap/velocity/target/Geyser-Velocity.jar
      
  gradle-build:
    runs-on: ubuntu-latest
    needs: check-build-type
    if: ${{ needs.check-build-type.outputs.build-type == 'gradle' }}
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v1
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Build with Gradle
        env: 
          BRANCH: ${{ needs.check-build-type.outputs.branch }}
        run: |
          git clone https://github.com/Kas-tle/Geyser.git --branch $BRANCH --single-branch
          cd Geyser
          git submodule update --init --recursive
          ./gradlew build --no-daemon
      - name: Archive artifacts (Geyser Standalone)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Standalone
          path: Geyser/bootstrap/standalone/build/libs/Geyser.jar
      - name: Archive artifacts (Geyser Spigot)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Spigot
          path: Geyser/bootstrap/spigot/build/libs/Geyser-Spigot.jar
      - name: Archive artifacts (Geyser BungeeCord)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser BungeeCord
          path: Geyser/bootstrap/bungeecord/build/libs/Geyser-BungeeCord.jar
      - name: Archive artifacts (Geyser Sponge)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Sponge
          path: Geyser/bootstrap/sponge/build/libs/Geyser-Sponge.jar
      - name: Archive artifacts (Geyser Velocity)
        uses: actions/upload-artifact@v2
        if: success()
        with:
          name: Geyser Velocity
          path: Geyser/bootstrap/velocity/build/libs/Geyser-Velocity.jar
