name: Upload Preview

on:
  workflow_dispatch:
    inputs:
      runId:
        required: true
        description: 'ID of the Build Pull Request Run'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - name: 'Download all artifacts'
        uses: actions/github-script@v3.1.0
        with:
          script: |
            const run_id = ${{ github.event.inputs.runId }};
            const artifacts = await github.actions.listWorkflowRunArtifacts({
               owner: context.repo.owner,
               repo: context.repo.repo,
               run_id: run_id,
            });

            // Loop through all artifacts and download them
            for (const artifact of artifacts.data.artifacts) {
              const download = await github.actions.downloadArtifact({
                 owner: context.repo.owner,
                 repo: context.repo.repo,
                 artifact_id: artifact.id,
                 archive_format: 'zip',
              });
              const fs = require('fs');
              // Write each artifact to a separate file named after the artifact
              fs.writeFileSync(`${{github.workspace}}/${artifact.name}.zip`, Buffer.from(download.data));
            }
      - name: 'Unzip artifacts'
        run: |
          mkdir -p ${{github.workspace}}/artifacts
          for zip in ${{github.workspace}}/*.zip; do
            unzip -d ${{github.workspace}}/artifacts "$zip"
          done