name: Upload Preview

on:
  workflow_dispatch:
    inputs:
      runId:
        required: true
        description: 'ID of the action to pull artifacts from'
      version:
        required: true
        description: 'Version under which to upload to the Downloads API'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@c850b930e6ba138125429b7e5c93fc707a7f8427
        with:
          run-id: ${{ github.event.inputs.runId }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-multiple: true
      - name: 'List Artifacts'
        run: |
          ls -a