name: Upload Preview

on:
  workflow_dispatch:
    inputs:
      runId:
        required: true
        description: 'ID of the Build Pull Request Run'

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          run-id: ${{ github.event.inputs.runId }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Unzip artifacts'
        run: |
          mkdir -p ${{github.workspace}}/artifacts
          for zip in ${{github.workspace}}/*.zip; do
            unzip -d ${{github.workspace}}/artifacts "$zip"
          done